import java.util.ArrayList;

public class ExemploArrayLis {
  public static void main(String [] args) {
	ArrayList<String> nomes = new ArrayList <String>();
	
	nomes.add("Larissa");
	nomes.add("Camila");
	nomes.add("Beatriz");
	
	System.out.println(nomes);
	
	ArrayList<Integer> numero = new ArrayList <Integer>();
	
	numero.add(17);
	numero.add(17);
	numero.add(17);
	
	System.out.println(numero);
	
	ArrayList<Double> altura = new ArrayList <Double>();
	
	altura.add(1.62);
	altura.add(1.58);
	altura.add(1.60);
	
	System.out.println(altura);
	

   }
}
